/** ESLint (flat config) — Vue 3 + Storybook design system.
 *
 *  Tuned for what this repo actually is: a prototype/design-system workspace
 *  where most "code" is Storybook stories built from runtime-compiled template
 *  strings. So the rules that earn their place are the ones that catch bugs
 *  that would otherwise show up as a blank story — an undefined binding, an
 *  unused import, a duplicated key — not stylistic preferences.
 *
 *  Formatting rules are deliberately absent. Nothing here reformats code.
 */
import js from '@eslint/js'
import vue from 'eslint-plugin-vue'
import ts from 'typescript-eslint'
import globals from 'globals'

export default [
  {
    ignores: [
      'node_modules/**',
      'storybook-static/**',
      'dist/**',
      'references/**',
      'creditCards/**',
      'background-img/**',
      '.netlify/**',
      'src/stories/_tokens-data.js', // generated by scripts/gen-tokens-data.mjs
      // A fill-in-the-blanks authoring template, not live code: its imports are
      // scaffolding for whoever copies it, so "unused" is the intended state.
      'docs/story-template.js',
    ],
  },

  js.configs.recommended,
  ...vue.configs['flat/recommended'],

  {
    /* Parts of this repo are TypeScript: standalone composables (.ts) and Vue
       SFCs using `<script setup lang="ts">`. Without a TS-aware parser those
       files fail to parse and are silently unlinted, which is worse than
       linting them loosely.

       The two need different wiring: a .ts file needs the TS parser directly,
       while a .vue file must keep vue-eslint-parser (it owns the SFC blocks)
       and hand only the script block to TS via parserOptions.parser. */
    files: ['**/*.ts'],
    languageOptions: { parser: ts.parser, ecmaVersion: 2023, sourceType: 'module' },
  },
  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: ts.parser, ecmaVersion: 2023, sourceType: 'module' },
    },
  },

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      /* Correctness — these are the ones that catch real breakage. */
      // `caughtErrors: 'none'` — ESLint 9 started flagging `catch (e) {}` where
      // the error is deliberately swallowed. That is a real pattern here (best-
      // effort parsing, optional browser APIs) and not a bug worth renaming.
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none',
      }],
      'no-undef': 'error',
      'no-dupe-keys': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      // A deliberately swallowed error is a real pattern here — localStorage
      // throws in private browsing, and there is nothing useful to do about it.
      'no-empty': ['error', { allowEmptyCatch: true }],

      /* Vue: keep the correctness rules, drop the house-style ones. This repo's
         stories are template strings, not SFC templates, so several of the
         recommended stylistic rules cannot see the markup they judge. */
      'vue/multi-word-component-names': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',
      'vue/first-attribute-linebreak': 'off',
      // Off for the same reason as the rest, plus one of its own: its autofix
      // deletes the leading indentation along with the blank line, so running
      // `--fix` actively makes the template worse.
      'vue/multiline-html-element-content-newline': 'off',
      'vue/require-default-prop': 'off',
      'vue/no-v-html': 'off',
    },
  },

  {
    /* Storybook stories: a `console` left in a story is noise, not a failure,
       and unused story exports are the whole point of the file. */
    files: ['**/*.stories.js', '**/*.stories.jsx'],
    rules: {
      'no-console': 'off',
    },
  },

  {
    /* Node scripts. */
    files: ['scripts/**/*.{js,mjs}', '*.config.js', '.storybook/**/*.js'],
    languageOptions: { globals: { ...globals.node } },
    rules: { 'no-console': 'off' },
  },
]
